### ISSUE TITLE
testing for /usr/sbin/useradd works only for root

### ISSUE THREAD

**Issue by oz123** [troglobit/libite#10]
While this can be okay, when running the test as root, this will fail if running as normal user (if path is not set to contain /usr/sbin/.
Should this be patched?

**Comment by troglobit** [comment]
Hmm, this would fail on Debian as well, I realize now.  My Ubuntu system is a bit too user-friendly with its default $PATH setting.

**Comment by troglobit** [comment]
This should work better.
