### ISSUE TITLE
Tests broken on debian

### ISSUE THREAD

**Issue by yangfl** [troglobit/libite#14]
```
FAIL: fexist
============

fexist: Failed fexist(/sbin/init): No such file or directory
File /etc/passwd does exist     => OK!
File /etc/kalle  does not exist => OK!
FAIL fexist (exit status: 1)

FAIL: which
===========

                  ls : hot dog --> /bin/ls
                free : Not hot dog
             modinfo : Not hot dog
             useradd : hot dog --> /usr/sbin/useradd
      /usr/bin/which : hot dog --> /usr/bin/which
         /bin/ps aux : Not hot dog
         /etc/passwd : Not hot dog
FAIL which (exit status: 3)
```

So it's really bad to bindly assume some files exist (for example `/sbin/init`, which is replaced by systemd in Debian). Better to use `stat()` or something to check their existence.

**Comment by troglobit** [comment]
That's an unnecessarily snide remark?

Tests work for me, on Ubuntu and Debian. The latter, both on Buster and testing.   Actually `/sbin/init` is the canonical hard-coded path that the Linux kernel uses as default init, unless `init=foo` is given on the kernel command line.  Debian (and Ubuntu) keep a symlink to `/lib/systemd/systemd` for this very purpose.

The whole point of the test is to verify the functionality of `which()`, which is a C function that implements which(1) using `stat()`.  I agree, however, that assuming hard-coded paths in the system is not good form.  I wrote this library for myself, for use in my own projects. Updating the test to first create a set of files, which the test then verifies, is a good solution.   If you want to use the library, I welcome cooperation. Your patch is welcome.
