### ISSUE TITLE
touch() does not update mtime on an existing file

### ISSUE THREAD

**Issue by ptruz** [troglobit/libite#6]
Documentation on the touch() helper function says:

Create a file, or update mtime. Errors on stderr

... but the touch() function in its current implementation will not update mtime if the file already exists.

**Comment by troglobit** [comment]
Good catch! Fixed in 628c559 :smiley: :+1: 

Probably best if you add that commit as a patch to the WeOS version.  I'm not planning any new libite (-lite) release before the summer break.
