### ISSUE TITLE
makepath functions signature

### ISSUE THREAD

**Issue by jesponde** [troglobit/libite#8]
Hi,

First, thanks for the very quick fix on the previous comment!

Back to code :-)

Wouldn'it be better to have __const char *dir__ input parameter for these two functions?
https://github.com/troglobit/libite/blob/be6f276557ab85cef4a8d681b2970990070d05c9/makepath.c#L32

https://github.com/troglobit/libite/blob/be6f276557ab85cef4a8d681b2970990070d05c9/makepath.c#L59

When passing **std:string::c_str()** for example, it would work without any cast.

Minor remark, this include is useless:
https://github.com/troglobit/libite/blob/be6f276557ab85cef4a8d681b2970990070d05c9/makepath.c#L22

Regards,

**Comment by troglobit** [comment]
Pull requests are most welcome :)

Also, please open a new issue instead of reusing a closed one.

**Comment by jesponde** [comment]
Please, forget the minor remark, I think I understood why it is important to keep "lite.h"
