### ISSUE TITLE
Tests broken on gentoo

### ISSUE THREAD

**Issue by oz123** [troglobit/libite#9]
at first I thought this has to do with the gcc version, but I now see it also fails with my gcc version.
But the failure is because of which?
```

========================================
   libite 2.0.0: tests/test-suite.log
========================================

# TOTAL: 14
# PASS:  13
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: which
===========

                  ls : hot dog --> /bin/ls
                free : hot dog --> /usr/bin/free
             modinfo : hot dog --> /sbin/modinfo
             useradd : hot dog --> /usr/sbin/useradd
          /bin/which : Not hot dog
         /bin/ps aux : hot dog --> /bin/ps
         /etc/passwd : Not hot dog
FAIL which (exit status: 1)

```

**Comment by oz123** [comment]
I am guessing it's because gentoo has which in `/usr/bin/which`.

**Comment by troglobit** [comment]
Yup, you're right. Bug in the unit test.

**Comment by troglobit** [comment]
Ubuntu has a symlink to from /usr/bin/which --> /bin/which ... testing.

**Comment by troglobit** [comment]
OK, pushing a fix in a moment.  However, I don't have a follow-up release planned yet, possibly for the New Year. So in the meantime you'll have to package the fix.

**Comment by oz123** [comment]
@troglobit , yeah, I can add a patch to the ebuild.
